parallel_occurances.cpp File Reference
parallel_occurances.cpp File Reference
#include <iostream>
#include <stdlib.h>
#include <string.h>
#include <pthread.h>
#include <errno.h>
Classes
struct COUNTING_THREAD_DATA
Functions
void * counting_thread_fun (void *thread_data)
counting_thread_fun is the function invoked by each thread
void error (string msg)
error function print error message on error stream
int main (int argc, char *argv[])
main function provides facility to process command line argument
Variables
pthread_mutex_t counting_mutex = PTHREAD_MUTEX_INITIALIZER
Mutex variable for synchronizing operation on count.
static int match_count = 0
int NO_OF_THREADS = 1
Static variable count.
Function Documentation
void * counting_thread_fun (void * thread_data)
counting_thread_fun is the function invoked by each thread
Parameters:
[in] thread_data is data passed to thread in form of structure
data is pointer to COUNTING_THREAD_DATA type of structure
checks for maismatch for data
Definition at line 72 of file parallel_occurances.cpp.
References COUNTING_THREAD_DATA::bigString, COUNTING_THREAD_DATA::bigStringLength, counting_mutex, match_count, COUNTING_THREAD_DATA::subString, and COUNTING_THREAD_DATA::subStringLength.
Referenced by main().
void error (string msg)
error function print error message on error stream
No of thread which are used to execute program.
Parameters:
[in] msg is error message
Definition at line 66 of file parallel_occurances.cpp.
Referenced by main().
int main (int argc, char * argv[])
main function provides facility to process command line argument
Parameters:
[in] argc is the number of count of command line argument passed.
[in] argv is array to pointer of characters to store arguments.
argv[1] is passed as bigger String
argv[2] is passed as smaller String
pthread_t array for containing threads id's
Definition at line 99 of file parallel_occurances.cpp.
References COUNTING_THREAD_DATA::bigString, COUNTING_THREAD_DATA::bigStringLength, counting_thread_fun(), error(), match_count, NO_OF_THREADS, COUNTING_THREAD_DATA::subString, and COUNTING_THREAD_DATA::subStringLength.
Variable Documentation
pthread_mutex_t counting_mutex = PTHREAD_MUTEX_INITIALIZER
Mutex variable for synchronizing operation on count.
Definition at line 60 of file parallel_occurances.cpp.
Referenced by counting_thread_fun().
int match_count = 0 [static]
Definition at line 62 of file parallel_occurances.cpp.
Referenced by counting_thread_fun(), and main().
int NO_OF_THREADS = 1
Static variable count.
Definition at line 64 of file parallel_occurances.cpp.
Referenced by main().