PrintSpiralMatrix: PrintSpiral.o spiral.o
	g++ -o PrintSpiralMatrix PrintSpiral.o spiral.o
PrintSpiral.o: PrintSpiral.cpp spiral.hpp
	g++ -Wall -c PrintSpiral.cpp
spiral.o: spiral.cpp spiral.hpp
	g++ -Wall -c spiral.cpp


